
import type { Metadata } from "next";
import { Inter, Fredoka } from "next/font/google";
import "./globals.css";
import Storeprovider from "@/redux/Storeprovider";
import AuthProvider from "@/app/providers/AuthProvider";

const bodyFont = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const displayFont = Fredoka({
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bodyFont.variable} ${displayFont.variable}`}>
      <body className="min-h-screen bg-app-bg text-app-fg">
        <Storeprovider>
          <AuthProvider>{children}</AuthProvider>
        </Storeprovider>
      </body>
    </html>
  );
}
